spring:
  application:
    name: oauth2-server
  # 配置数据库信息
  datasource:
    # 数据源配置
    username: postgres
    password: 123456
    #    url: jdbc:postgresql://192.168.50.49:5432/postgres?useUnicode=true&characterEncoding=utf-8&useSSL=false
    jdbc-url: jdbc:postgresql://192.168.50.49:5432/postgres?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  #thymeleaf
  thymeleaf:
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
#  resources:
#    static-locations:
#    - classpath:/META-INF/resources/
#    - classpath:/resources/
#    - classpath:/static/
#    - classpath:/public/
#  mvc:
#    static-path-pattern: /**
server:
  port: 9090
mybatis:
  type-aliases-package: com.zegobird.oauth2.domain
  mapper-locations: classpath:mapper/*.xml

zegobird:
  security:
    browser:
      loginPage: /login.html
      loginType: REDIRECT