
spring:
  application:
    name: authorizationserver
  # 配置数据库信息
  datasource:
    # 数据源配置
    username: postgres
    password: 123456
    #    url: jdbc:postgresql://192.168.50.49:5432/postgres?useUnicode=true&characterEncoding=utf-8&useSSL=false
    jdbc-url: jdbc:postgresql://192.168.50.49:5432/postgres?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

server:
  port: 9090
mybatis:
  type-aliases-package: com.zegobird.oauth2.domain
  mapper-locations: classpath:mapper/*.xml